# Definicion de la ontologia
define

# Entidades:

"muestra-de-suelo"              sub entity
    has tipo-de-suelo
    has porcentaje-de-arcilla
    has nivel-de-ph
    has ph
    has salinidad
    has conductividad-electrica
    has nivel-de-material-organico-contenido
    has porcentaje-de-material-organico
    has fosforo
    has potasio
    has nitrogeno
    has contaminacion
    has permite-absorcion-de-agua
    has apto-para-cultivo
    plays sometido-por;

"cultivo"                       sub entity
    has nombre-del-cultivo
    has ph-minimo
    has ph-maximo
    has necesidad-de-fosforo
    has necesidad-de-potasio
    has necesidad-de-nitrogeno
    plays cultivo-comparacion;

"diagnostico-de-compatibilidad" sub entity
    has compatibilidad
    plays sometedor-de
    plays compatibilidad-comparacion
    plays recomendante;

"recomendacion-de-fertilizante" sub entity
    has fosforo-a-agregar
    has nitrogeno-a-agregar
    has potasio-a-agregar
    plays recomendado;

# -------------------------------------------

# Atributos

## Atributos de muestra-de-suelo
"tipo-de-suelo"                         sub attribute datatype string;
"porcentaje-de-arcilla"                 sub attribute datatype long;
"nivel-de-ph"                           sub attribute datatype string;
"ph"                                    sub attribute datatype long;
"salinidad"                             sub attribute datatype string;
"conductividad-electrica"               sub attribute datatype long;
"nivel-de-material-organico-contenido"  sub attribute datatype string;
"porcentaje-de-material-organico"       sub attribute datatype long;
"fosforo"                               sub attribute datatype double;
"potasio"                               sub attribute datatype double;
"nitrogeno"                             sub attribute datatype double;
"contaminacion"                         sub attribute datatype boolean;
"permite-absorcion-de-agua"             sub attribute datatype boolean;
"apto-para-cultivo"                     sub attribute datatype boolean;

## Atributos de cultivo
"nombre-del-cultivo"                    sub attribute datatype string;
"ph-minimo"                             sub attribute datatype double;
"ph-maximo"                             sub attribute datatype double;
"necesidad-de-fosforo"                  sub attribute datatype double;
"necesidad-de-potasio"                  sub attribute datatype double;
"necesidad-de-nitrogeno"                sub attribute datatype double;

## Atributos de diagnostico-de-compatibilidad
"compatibilidad"                        sub attribute datatype boolean;

## Atributos de recomendacion-de-fertilizante
"fosforo-a-agregar"                     sub attribute datatype double;
"nitrogeno-a-agregar"                   sub attribute datatype double;
"potasio-a-agregar"                     sub attribute datatype double;

# -------------------------------------------

# Relaciones

"hace-una"          sub relationship 
    relates recomendado
    relates recomendante;

"se-somete-a"       sub relationship 
    relates sometido-por
    relates sometedor-de;

"se-compara-en"     sub relationship 
    relates cultivo-comparacion
    relates compatibilidad-comparacion;

# -------------------------------------------

# Roles

## Roles de hace-una
"recomendado"                   sub role;
"recomendante"                  sub role;

## Roles de se-somete-a
"sometido-por"                  sub role;
"sometedor-de"                  sub role;

## Roles de se-compara-en
"cultivo-comparacion"           sub role;
"compatibilidad-comparacion"    sub role;